on: [push, pull_request]

name: Test

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      NASA_API_KEY_TEST: ${{ secrets.NASA_API_KEY_TEST }}

    steps:
      - name: Copy files from repo
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      
      - name: Run Ruff
        run: poetry run task lint
      
      - name: Run Radon
        run: poetry run task radon

      - name: Run Tests
        run: poetry run task test

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov